# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

workspace 'Example'

inhibit_all_warnings!
use_frameworks!

target 'UIKitPlusExample' do
    pod 'UIKit-Plus', :path => '../'
end
